global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'prod-monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"
  - "alert.rules"
  #- "jenkins_test.rules"

scrape_configs:

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'prod-jenkins.example.com:9100'
          #- 'alexf-jenkins.example.com:9100'

  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets:
          - 'prod-jenkins.example.com:9200'
          #- 'alexf-jenkins.example.com:9200'

  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://prod-jenkins.example.com
        #- https://alexf-jenkins.example.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: REAL_IP:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
